"""empty message

Revision ID: ee7ed5bd337e
Revises: 
Create Date: 2022-05-10 03:34:43.020748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7ed5bd337e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('isEmpty', sa.Boolean(), nullable=True),
    sa.Column('pumpActive', sa.Boolean(), nullable=True),
    sa.Column('pumpDuration', sa.Float(), nullable=True),
    sa.Column('pumpInterval', sa.Float(), nullable=True),
    sa.Column('lightLevel', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('soilMoisture', sa.Float(), nullable=True),
    sa.Column('soilMoistureTarget', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    # ### end Alembic commands ###
